version: "3.7"

services:
  client:
    image: ymwambeyu/yolo-frontend:v1.0.0
    container_name: yolo-e-comm-frontend
    #build: ./client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    image: ymwambeyu/yolo-backend:v1.0.0
    container_name: yolo-e-comm-backend
    #build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - mongodb_url=mongodb://127.0.0.1:27017
    networks:
      - my-network
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - my-network

volumes:
  data:


networks:
  my-network:
    driver: bridge
