version: "3.8"

services:
  client:
    build:
      context: ./client 
      dockerfile: Dockerfile
    container_name: node-frontend
    ports:
      - "3000:3000"
    networks:
      - network_bridge
    image: yakub/node-frontend:latest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - "5000:5000"
    networks:
      - network_bridge
    image: yakub/node-backend:latest

  database:
    image: mongo:latest
    container_name: mongo-db
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "27017:27017"

    networks:
      - network_bridge
      
networks:
  network_bridge:
    driver: bridge      