- name: 
  hosts: all
  become: true
  vars:
    repo_url: https://github.com/flaseen/yolo.git
    user: ubuntu
    dest: /home/{{ user }}/yolo

  roles:
    - connectivity-test
    - updating-server
    - installing-docker
    - cloning-repo