- name: 
  hosts: all
  become: true
  vars:
    repo_url: https://github.com/flaseen/yolo.git
    user: developer
    dest: /home/{{ user }}/yolo

  roles:
    - connectivity-test
    - updating-server
    - installing-docker
    - cloning-repo
    - deploying-docker-containers